GET http://localhost:3002/api/loadGraves

###

POST http://localhost:3002/api/addDead
Content-Type: application/json

{
  "newGrave": {
    "firstName": "Etunimi",
    "lastName": "Sukunimi",
    "birthday": "01/01/1950",
    "died": "01/01/2005",
    "cemetery": "Kellonummen hautausmaa",
    "category": "politics",
    "location": {
      "lat": 12345.123,
      "long": 1234.123
    }
  }
}

###

POST http://localhost:3002/api/newUser
Content-Type: application/json

{
  "username": "Testi",
  "password": "Salainen"
}

###

GET http://localhost:3002/api/search?name=sauli
Content-Type: application/json

###

PUT http://localhost:3002/api/updateCemetery
Content-Type: application/json

{
  "name": "Sauli Niinistö",
  "newGrave": "Kellonummen hautausmaa2"
}